### ISSUE TITLE
Doesn't seem to listen on IPv6

### ISSUE THREAD

**Issue by kseistrup** [TheKysek/MiNode#1]
While MiNode connects to IPv6 nodes without any problems, it doesn't seem to listen on IPv6. Using `netstat(8)` I do see

```
tcp        0      0 0.0.0.0:8444            0.0.0.0:*               LISTEN      19564/python
```

but I would also expect a line like this:

```
tcp6       0      0 :::8444                 :::*                    LISTEN      19564/python
```

**Comment by kseistrup** [comment]
More details:

Creating an IPv4 listener before an IPv6 listener gives the following error message:

```
[2016-07-30 11:10:58,478] [ERROR] Error while starting IPv6 listener                                                                                      
[2016-07-30 11:10:58,478] [ERROR] [Errno 98] Address already in use                                                                                       
```

and while MiNode will happily create outgoing IPv6 connections, it only accepts incoming IPv4 connections.

If, however, the IPv6 listener is created _before_ the IPv4 listener, MiNode comes with a similar error message:

```
[2016-07-30 11:17:09,254] [ERROR] Error while starting IPv4 listener                                                                                      
[2016-07-30 11:17:09,255] [ERROR] [Errno 98] Address already in use                                                                                       
```

but will accept incoming connections on IPv6 _and_ IPv4.

**Comment by kseistrup** [comment]
I was also wondering if the creation of an IPv6 listener should only be attempted if IPv6 is actually available:

``` py
if socket.has_ipv6:
    create_ipv6_listener()
create_ipv4_listener()
```

**Comment by TheKysek** [comment]
Thanks for reporting. Both IPv4 and v6 connections are accepted. Resolved by https://github.com/TheKysek/MiNode/commit/71fda58a3bfd24d79d2a9231a8110b251eee1e0c

**Comment by kseistrup** [comment]
The commit looks nice. However, an uncaught exception now happens in `listener.py`:

``` pytb
Exception in thread Listener:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "…/MiNode/src/listener.py", line 21, in run
    self.s.listen(1)
OSError: [Errno 98] Address already in use
```
