### ISSUE TITLE
Uncaught exceptions: ssl.SSLError and ConnectionResetError

### ISSUE THREAD

**Issue by kseistrup** [TheKysek/MiNode#10]
The three exceptions shown here were all seen multiple times with the current git version during the last 24 hours:

``` pytb
Exception in thread Connection to ${UNDISCLOSED_IP_ADDRESS}:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "…/minode/src/connection.py", line 92, in run
    self._send_data()
  File "…/minode/src/connection.py", line 128, in _send_data
    amount = self.s.send(self.buffer_send)
  File "/usr/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
ssl.SSLError: [SSL: UNEXPECTED_RECORD] unexpected record (_ssl.c:1844)
```

``` pytb
Exception in thread Connection to ${UNDISCLOSED_IP_ADDRESS}:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "…/minode/src/connection.py", line 92, in run
    self._send_data()
  File "…/minode/src/connection.py", line 128, in _send_data
    amount = self.s.send(self.buffer_send)
  File "/usr/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```

``` pytb
Exception in thread Connection to ${UNDISCLOSED_IP_ADDRESS}:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "…/minode/src/connection.py", line 92, in run
    self._send_data()
  File "…/minode/src/connection.py", line 128, in _send_data
    amount = self.s.send(self.buffer_send)
  File "/usr/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
ssl.SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:1844)
```

**Comment by TheKysek** [comment]
Issue no longer relevant.
