### ISSUE TITLE
Uncaught exception: AssertionError

### ISSUE THREAD

**Issue by kseistrup** [TheKysek/MiNode#7]
``` pytb
Exception in thread Connection to ${IP_ADDRESS_AND_PORT}:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "…/MiNode/src/connection.py", line 76, in run
    self._process_buffer()
  File "…/MiNode/src/connection.py", line 173, in _process_buffer
    self._process_message(m)
  File "…/MiNode/src/connection.py", line 200, in _process_message
    inv = message.Inv.from_message(m)
  File "…/MiNode/src/message.py", line 161, in from_message
    assert vector_count == len(vectors)
AssertionError
```

**Comment by TheKysek** [comment]
Resolved by 29ebdc44c9dacbf09ebbc0b9d3a5128d470809dd
